### ISSUE TITLE
Did you ever run an experiment?

### ISSUE THREAD

**Issue by lucidrains** [742617000027/nBRC#1]
I'm curious if this works as well as what the paper claims

**Comment by 742617000027** [comment]
Not to the point I would feel comfortable making statements about the validity of what the paper claims. I set up a **[Google Colab notebook](https://colab.research.google.com/drive/1meiWR1hOu7ksEV2reaT_texwNc4JWaJv?usp=sharing)** where an nBRC model and an LSTM model are trained for the Denoising benchmark. It's all very simple but feel free to play around with that and draw your own conclusions!

**Comment by lucidrains** [comment]
Ok thanks! I shall try it out :)
